### ISSUE TITLE
Detect Jenkins-specific idiosyncrasies with Groovy property syntax

### ISSUE THREAD

**Issue by hakanai** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#107]
I had a Jenkins shared library vars script doing this:

```groovy
boolean isUnixCached = isUnix()
```

CodeNarc then complained, telling me to change it to this:

```groovy
boolean isUnixCached = unix
```

I did this, and all the code compiled and passed the rest of the checks, but then when Jenkins actually tried to run it, it decided that there was no `unix` property on `nameOfMyVarsScript` and failed the build.

So I guess that built-in Jenkins methods _cannot_ be converted to property style access for some unknown reason.

Maybe there is a way to detect that automatically?

**Comment by mkobit** [comment]
This is most likely due to the way that the the Jenkins plugins containing `isUnix()` is written as something like a function in [this Jenkins plugin](https://github.com/jenkinsci/workflow-basic-steps-plugin/blob/67fffaed1f2a764c36212ab6af3c26c0a04939dc/src/main/java/org/jenkinsci/plugins/workflow/steps/IsUnixStep.java#L59-L74). CodeNarc isn't going to know about this, so I think you'd want to suppress CodeNarc for this particular problem. I don't think there is anything to be fixed here.

**Comment by hakanai** [comment]
Hence why it was written as a feature request. But isn't it a little weird to close it as "completed"? More like "rejected", if I'm getting the gist.
