### ISSUE TITLE
Add support for CpsScript

### ISSUE THREAD

**Issue by sruehl** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#43]
using type CpsScript result in a compilation error. With 0.4.0 you added support for NonCPS without using special dependencies. Can you add this support for CpsScript too?

**Comment by sruehl** [comment]
FYI: this is currently the dependency set I need to make the compile error go away:
```//////
    // Used for cps script
    implementation("org.kohsuke.stapler:stapler:1.253@jar")
    implementation("org.jenkins-ci.main:jenkins-core:2.89.2@jar")
    implementation("org.jenkins-ci.plugins.workflow:workflow-api:2.24@jar")
    implementation("org.jenkins-ci.plugins.workflow:workflow-cps:2.42@jar")
    //////```

**Comment by sruehl** [comment]
Background: In a library groovy class I want to access steps. For this I pass a reference of `this` from the calling script into the class and then use this reference to call the steps. No I wanted to type this reference to use @Delegate.

**Comment by mkobit** [comment]
I think overall, this request makes sense. There may be other references to Jenkins plugin and other types that are desired for use in a pipeline.

One tough thing here, at least for the unit testing side, is getting the right classpath for usage with Jenkins Pipeline Unit (or other unit tests that don't want to deal too much with Jenkins plugins and what not). `@NonCPS` is easier to handle because it is just an annotation and doesn't need to be present at runtime but those other references will require some additional dependency management code.

Do you have a minimal example of both the library and a `Jenkinsfile` to demonstrate:

* Where you need to reference the `CpsScript` type
* If you use any declared methods on `CpsScript`? (implementation seems to support Groovy's dynamic parts)

I've gotten around this in the past by using the `def` type. Code sort of like the following:

Library:
```
package things
class ThingDoer {
  void doSomeThings(def script) {
    script.sh('echo "hello"')
  }

  void doThingsAnd(def script, Closure body) {
    body.delegate = Closure.DELEGATE_FIRST
    body.delegate = script
    doSomeThings(script)
    body()
  }
}
```
Jenkinsfile:

```
@Library('lib')
import things.ThingDoer
ThingDoer
def doer = new ThingDoer()
doer.doSomeThings(this)
doer.doThingsAnd(script) {
  echo 'hello world'
}
```

**Comment by sruehl** [comment]
No currently I have no working example, as I had problems with the unit test but using your example the code would look like this:
```
package things
class ThingDoer {

  @Delegate
  CpsScript cpsScript
   ....
  def updateStuff() {
   node("Docker") {
     checkout(scm)
     ...
     cleanWs()
   }
  }
}
```

```
@Library('lib')
import things.ThingDoer
ThingDoer
def doer = new ThingDoer(cpsScript:this)
doer.updateStuff()
```

**Comment by mkobit** [comment]
Got it. That use case makes to me. I'm surprised (but glad) that the Groovy CPS compilation handles it.

You might be able to get away with using the dynamic type for now, but I'll add this to the next release:

```groovy
package things
class ThingDoer {

  @Delegate
  def cpsScript
   ....
  def updateStuff() {
   node("Docker") {
     checkout(scm)
     ...
     cleanWs()
   }
  }
}
```
Adding this to the next release.

**Comment by sruehl** [comment]
sorry, I didn't meant to close this, must be an problem with the touchscreen :(
