### ISSUE TITLE
How do I globally activate @TypeChecked for all files using this plugin?

### ISSUE THREAD

**Issue by vickychijwani** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#69]
Hi! :wave: Many thanks for this plugin, it helped me quickly setup integration testing for my shared library.

Coming to the issue: the Gradle docs describe a method to turn on static type-checking for all files like so ([link](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.GroovyCompileOptions.html#org.gradle.api.tasks.compile.GroovyCompileOptions:configurationScript)):

```groovy
import groovy.transform.TypeChecked
withConfig(configuration) {
    ast(TypeChecked)
}
```

[This StackOverflow answer](https://stackoverflow.com/a/30307025) provides a more complete example of the same. Unfortunately that doesn't work with this plugin - the `ast(...)` method isn't available for some reason. I also tried adding `apply plugin: groovy` before it, but with no success.

Any ideas how to get global type-checking working?

**Comment by mkobit** [comment]
The `groovy` plugin from Gradle is applied with this plugin. I see zero documentation of this `groovyc` feature of Groovy, but it seems to go down to [these lines of code](https://github.com/apache/groovy/blob/6b6cc275db660a848f768d691b6a43b01bbe7e73/src/main/groovy/groovy/ui/GroovyMain.java#L307-L319).

You should be able to do the same thing as described in Stack Overflow. In my example project:

`config/groovy/compiler-config.groovy`
```groovy
import groovy.transform.TypeChecked

withConfig(configuration) {
  ast(TypeChecked)
}
```

`build.gradle.kts`
```kotlin
tasks {
  "compileGroovy"(GroovyCompile::class) {
    groovyOptions.configurationScript = file("config/groovy/compiler-config.groovy")
  }
}
```

That is a Kotlin build script, but it should be similar for Groovy:
```groovy
tasks {
  compileGroovy {
    groovyOptions.configurationScript = file("config/groovy/compiler-config.groovy")
  }
}
```

Do note that this configuration will only aid you in development as Jenkins will compile it differently, and it might be difficult to use `TypeChecked` in particular because of the dynamic nature of steps.

Does that work for you?

**Comment by vickychijwani** [comment]
That worked! I think I was making a mistake somewhere.

> Do note that this configuration will only aid you in development as Jenkins will compile it differently, and it might be difficult to use TypeChecked in particular because of the dynamic nature of steps.

I understand - I only want this for development. Since I'm not relying on too many steps, I've defined my own interface to allow type-checking those methods as well, and I perform a type-coercion to said interface using `this as JenkinsDslMethods` so the type-checking works for steps too :slightly_smiling_face:
